"""
Rewrote and Solved: 12/01/13

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

__author__ = 'Johnny Dave'

fib = 1
answer = 0
solution = 0

for number in range(0, 4000000):
    hold = fib
    fib += answer
    answer = hold
    if fib % 2 == 0:
        solution += fib
    if fib >= 4000000:
        break

print solution
