// EP2.cpp : Defines the entry point for the console application.
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include "stdafx.h"
#include <iostream>
#include <math.h>

using namespace std;

int _tmain(int argc, _TCHAR* argv[])
{
	int exit = 1;

	do{
		int fab;
		int answer;
		int i;
		int hold;
		double solution = 0;

		fab = 1;
		answer = 0;
		
		for(i = 1; fab < 4000000; i++)
		{
			hold = fab;
			fab = fab + answer;
			answer = hold;
			if(!(fab % 2 != 0))
				solution += fab;
		}
		
		//cout << solution;
		printf("%10e",solution);

		cin >> exit;

	}while(exit != 2);
	return 0;
}

